### PR TITLE
Fix curated list creation

### LINKED ISSUE #39: Resolve outstanding issues with curated list creation via form
Form is presently not successfully making a post request. Known issues:
 - Need to send a "slug" hyphenated form of the name as part of the body

### PR DESCRIPTION
**Pull request by DanielEFrampton**
## Issues resolved
Resolves #39 (mostly, see below)

## Problem
Clicking "create curated list" on form on reading list dash was not successfully creating a new curated list.

## Solution
Updated controller's create action to expect a "slug" parameter, and updated NewList form to create one dynamically from the name and include it in the body of the POST request.

## Further known issues
- List of user's curated lists doesn't refresh, have to manually refresh page
- (related) Fields remain filled after clicking submit
- Some intermittent weird behavior still around changing fields, seeing that post error from honeybadger

### CODE REVIEW

File: app/controllers/curated_lists_controller.rb [hunk 1]
```diff
@@ -1,15 +1,17 @@
 class CuratedListsController < ApplicationController
   def show
-    found_list = CuratedList.where('user_id = ? AND slug = ?', id_for_username(params[:username]), params[:slug]).first.to_json
```
Comment (Tristan-Holtz) [inline app/controllers/curated_lists_controller.rb:3]: I assume the quotes change was a linting issue?

**Review by Tristan-Holtz — APPROVED** [review]
